services:
  redis_server_7000:
    build:
      dockerfile: redis-server.Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ./redis-server/test-cluster/7000/redis.conf:/etc/redis/redis.conf
    command: /etc/redis/redis.conf
    networks:
      redis_network:
        ipv4_address: 172.20.0.10
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "172.20.0.10", "-p", "7000", "ping"]
      interval: 10s
      start_period: 3s

  redis_server_7001:
    build:
      dockerfile: redis-server.Dockerfile
    ports:
      - "7001:7001"
    volumes:
      - ./redis-server/test-cluster/7001/redis.conf:/etc/redis/redis.conf
    command: /etc/redis/redis.conf
    networks:
      redis_network:
        ipv4_address: 172.20.0.11
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "172.20.0.11", "-p", "7001", "ping"]
      interval: 10s
      start_period: 3s

  redis_server_7002:
    build:
      dockerfile: redis-server.Dockerfile
    ports:
      - "7002:7002"
    volumes:
      - ./redis-server/test-cluster/7002/redis.conf:/etc/redis/redis.conf
    command: /etc/redis/redis.conf
    networks:
      redis_network:
        ipv4_address: 172.20.0.12
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "172.20.0.12", "-p", "7002", "ping"]
      interval: 10s
      start_period: 3s

  redis_server_7003:
    build:
      dockerfile: redis-server.Dockerfile
    ports:
      - "7003:7003"
    volumes:
      - ./redis-server/test-cluster/7003/redis.conf:/etc/redis/redis.conf
    command: /etc/redis/redis.conf
    networks:
      redis_network:
        ipv4_address: 172.20.0.13
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "172.20.0.13", "-p", "7003", "ping"]
      interval: 10s
      start_period: 3s

  redis_server_7004:
    build:
      dockerfile: redis-server.Dockerfile
    ports:
      - "7004:7004"
    volumes:
      - ./redis-server/test-cluster/7004/redis.conf:/etc/redis/redis.conf
    command: /etc/redis/redis.conf
    networks:
      redis_network:
        ipv4_address: 172.20.0.14
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "172.20.0.14", "-p", "7004", "ping"]
      interval: 10s
      start_period: 3s

  redis_server_7005:
    build:
      dockerfile: redis-server.Dockerfile
    ports:
      - "7005:7005"
    volumes:
      - ./redis-server/test-cluster/7005/redis.conf:/etc/redis/redis.conf
    command: /etc/redis/redis.conf
    networks:
      redis_network:
        ipv4_address: 172.20.0.15
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "172.20.0.15", "-p", "7005", "ping"]
      interval: 10s
      start_period: 3s

  redis_server_7006:
    build:
      dockerfile: redis-server.Dockerfile
    ports:
      - "7006:7006"
    volumes:
      - ./redis-server/test-cluster/7006/redis.conf:/etc/redis/redis.conf
    command: /etc/redis/redis.conf
    networks:
      redis_network:
        ipv4_address: 172.20.0.16
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "172.20.0.16", "-p", "7006", "ping"]
      interval: 10s
      start_period: 3s

  redis_server_7007:
    build:
      dockerfile: redis-server.Dockerfile
    ports:
      - "7007:7007"
    volumes:
      - ./redis-server/test-cluster/7007/redis.conf:/etc/redis/redis.conf
    command: /etc/redis/redis.conf
    networks:
      redis_network:
        ipv4_address: 172.20.0.17
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "172.20.0.17", "-p", "7007", "ping"]
      interval: 10s
      start_period: 3s

  redis_server_7008:
    build:
      dockerfile: redis-server.Dockerfile
    ports:
      - "7008:7008"
    volumes:
      - ./redis-server/test-cluster/7008/redis.conf:/etc/redis/redis.conf
    command: /etc/redis/redis.conf
    networks:
      redis_network:
        ipv4_address: 172.20.0.18
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "172.20.0.18", "-p", "7008", "ping"]
      interval: 10s
      start_period: 3s

  cluster_configurator:
    build:
      dockerfile_inline: |
        FROM debian:bullseye-slim
        RUN apt-get update && apt-get install -y redis-tools && rm -rf /var/lib/apt/lists/*
    command:
      bash /config-cluster.conf
    volumes:
      - ./config-cluster.sh:/config-cluster.conf
    depends_on:
      redis_server_7000:
        condition: service_healthy
      redis_server_7001:
        condition: service_healthy
      redis_server_7002:
        condition: service_healthy
      redis_server_7003:
        condition: service_healthy
      redis_server_7004:
        condition: service_healthy
      redis_server_7005:
        condition: service_healthy
      redis_server_7006:
        condition: service_healthy
      redis_server_7007:
        condition: service_healthy
      redis_server_7008:
        condition: service_healthy
    networks:
      - redis_network

  docs_syncer:
    build:
      dockerfile: docs-syncer.Dockerfile
    environment:
      REDIS_HOST: 172.20.0.16
      REDIS_PORT: 7006
    depends_on:
      cluster_configurator:
        condition: service_completed_successfully
        restart: true
    networks:
      - redis_network

  docs_gpt:
    build:
      dockerfile: docs-gpt.Dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:?}
      REDIS_HOST: 172.20.0.16
      REDIS_PORT: 7006
    depends_on:
      cluster_configurator:
        condition: service_completed_successfully
        restart: true
    networks:
      - redis_network

networks:
  redis_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
